#!/usr/bin/env python3
class MyClass:

    def __call__(self, *args, **kwds):
        print("I was called with", args, kwds)
        
    def __init__(self):
        print("I was initialized")
        
        
        
o1 = MyClass()
o1()
